version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing...
  build:
    commands:
      - echo Building artifact...
      - pwd
      - ls -la
      - zip -r webapp.zip . -x buildspec.yml .git/*

artifacts:
  files:
    - webapp.zip

